
proc:
  src:
    name: "suggestBank" 
    conn_type: 'rest2json'
    conn_params:
      retries: 2
      timeout: 30  
      spec_url: ['htt1ps://dadata.ru/files/openapi/suggestions.yml','file://C:/Users/kdenis/Documents/Work/OpenApiSpecParser/examples/suggestions.yml']
    data:
      payload: [{"query": "BKCHRUMM"},{"query": "SLOMANNIY"},{"query": "ALFARUMM"}]
      type_mapping_override:
        "null": "null"
  transform:
    enabled: false
  tgt:
auth:
  src:
    header: 
      "Authorization":  "Token 2d2ef7d8f14f46f033ca83198d8b00cf9b83837d"
      "X-Secret": "34ad3a7185bff656155cbd52e05d5eff3ce1f489"
env:
  json:
    type_mapping:
      int32: integer
      int64: long
      float: float
      double: double
      date: string
      date-time: string
      binary: binary
    headers_fallback:
      Content-type : string    

